/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Outfit", "system-ui", "-apple-system", "sans-serif"],
        serif: ["Cormorant Garamond", "Georgia", "serif"],
        display: ["Cormorant Garamond", "Georgia", "serif"],
        body: ["Plus Jakarta Sans", "Outfit", "system-ui", "-apple-system", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        tibetan: ["Noto Serif Tibetan", "serif"],
        "tibetan-scholarly": ["Jomolhari", "Noto Serif Tibetan", "serif"],
        "tibetan-display": ["Monlam Uni Ouchan3", "Noto Serif Tibetan", "serif"],
        headerLinks: ["Plus Jakarta Sans", "sans-serif"],
        siteTitle: ["Cormorant Garamond", "Georgia", "serif"],
        sectionTitle: ["Cormorant Garamond", "Georgia", "serif"],
        button: ["Plus Jakarta Sans", "sans-serif"],
        quote: ["Cormorant Garamond", "Georgia", "serif"],
      },
      colors: {
        bg: "var(--bg)",
        ink: "var(--fg)",
        fg: "var(--fg)",
        muted: "var(--muted)",
        surface: "var(--surface)",
        "surface-subtle": "var(--surface-subtle)",
        "surface-muted": "var(--surface-subtle)",
        "surface-high": "var(--surface)",
        accent: "var(--accent)",
        "accent-soft": "var(--accent-hover)",
        "accent-hover": "var(--accent-hover)",
        "accent-subtle": "var(--accent-subtle)",
        "accent-secondary": "var(--accent-secondary)",
        "accent-secondary-hover": "var(--accent-secondary-hover)",
        "accent-secondary-subtle": "var(--accent-secondary-subtle)",
        "accent-tertiary": "var(--accent-tertiary)",
        "accent-tertiary-hover": "var(--accent-tertiary-hover)",
        "accent-tertiary-subtle": "var(--accent-tertiary-subtle)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        gold: "var(--gold)",
        saffron: "var(--saffron)",
        maroon: {
          DEFAULT: "var(--maroon)",
          dark: "var(--maroon-dark)",
          light: "var(--maroon-light)",
          surface: "var(--maroon-surface)",
          border: "var(--maroon-border)",
        },
        success: "var(--success)",
        "success-subtle": "var(--success-subtle)",
        warning: "var(--warning)",
        "warning-subtle": "var(--warning-subtle)",
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "8px",
        md: "12px",
        lg: "16px",
        "2xl": "16px",
        "3xl": "24px",
        full: "9999px",
      },
      boxShadow: {
        xs: "0 1px 2px rgba(26, 22, 21, 0.04)",
        sm: "0 1px 3px rgba(26, 22, 21, 0.04), 0 1px 2px rgba(26, 22, 21, 0.02)",
        md: "0 4px 12px rgba(26, 22, 21, 0.06), 0 1px 3px rgba(26, 22, 21, 0.04)",
        lg: "0 12px 28px rgba(26, 22, 21, 0.08), 0 4px 10px rgba(26, 22, 21, 0.04)",
        card: "0 4px 12px rgba(26, 22, 21, 0.06), 0 1px 3px rgba(26, 22, 21, 0.04)",
        soft: "0 10px 30px -10px rgba(0, 0, 0, 0.08)",
        glow: "0 0 20px rgba(198, 127, 27, 0.35)",
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
        drawLine: {
          to: { strokeDashoffset: "0" },
        },
        drawKnot: {
          to: { strokeDashoffset: "0" },
        },
        slowSpin: {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
        float: "float 5s ease-in-out infinite",
        "draw-line": "drawLine 2s cubic-bezier(0.2, 0.8, 0.2, 1) forwards",
        "draw-knot": "drawKnot 1.8s ease-in-out forwards",
        "slow-spin": "slowSpin 60s linear infinite",
      },
    },
  },
  plugins: [],
};
