/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Outfit", "system-ui", "-apple-system", "sans-serif"],
        serif: ["Jomolhari", "Noto Serif Tibetan", "Georgia", "serif"],
        display: ["Jomolhari", "Noto Serif Tibetan", "Georgia", "serif"],
        body: ["Plus Jakarta Sans", "Outfit", "system-ui", "-apple-system", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        tibetan: ["Monlam Uni Ouchan3", "Noto Serif Tibetan", "serif"],
        headerLinks: ["Plus Jakarta Sans", "sans-serif"],
        siteTitle: ["Jomolhari", "serif"],
        sectionTitle: ["Jomolhari", "serif"],
        button: ["Plus Jakarta Sans", "sans-serif"],
        quote: ["Jomolhari", "serif"],
      },
      colors: {
        bg: "var(--bg)",
        ink: "var(--fg)",
        fg: "var(--fg)",
        muted: "var(--muted)",
        surface: "var(--surface)",
        "surface-subtle": "var(--surface-subtle)",
        "surface-muted": "var(--surface-subtle)",
        "surface-high": "var(--surface)",
        accent: "var(--accent)",
        "accent-soft": "var(--accent-hover)",
        "accent-hover": "var(--accent-hover)",
        "accent-subtle": "var(--accent-subtle)",
        "accent-secondary": "var(--accent-secondary)",
        "accent-secondary-subtle": "var(--accent-secondary-subtle)",
        "accent-tertiary": "var(--accent-tertiary)",
        "accent-tertiary-subtle": "var(--accent-tertiary-subtle)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        gold: "var(--accent-secondary)",
        saffron: "var(--accent-secondary)",
      },
      boxShadow: {
        xs: "0 1px 2px rgba(26, 22, 21, 0.05)",
        sm: "0 2px 4px rgba(26, 22, 21, 0.06)",
        md: "0 4px 12px rgba(26, 22, 21, 0.08)",
        lg: "0 12px 24px -4px rgba(26, 22, 21, 0.10)",
        card: "0 4px 16px rgba(26, 22, 21, 0.08)",
        soft: "0 10px 30px -10px rgba(0, 0, 0, 0.08)",
        glow: "0 0 20px rgba(198, 127, 27, 0.35)",
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
        drawLine: {
          to: { strokeDashoffset: "0" },
        },
        drawKnot: {
          to: { strokeDashoffset: "0" },
        },
        slowSpin: {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
        float: "float 5s ease-in-out infinite",
        "draw-line": "drawLine 2s cubic-bezier(0.2, 0.8, 0.2, 1) forwards",
        "draw-knot": "drawKnot 1.8s ease-in-out forwards",
        "slow-spin": "slowSpin 60s linear infinite",
      },
    },
  },
  plugins: [],
};
